name: winnf3
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - attrs=23.1.0
  - blas=1.0
  - blosc=1.21.3
  - boost-cpp=1.82.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.12.12
  - cairo=1.16.0
  - cartopy=0.22.0
  - certifi=2024.2.2
  - cffi=1.16.0
  - cfitsio=3.470
  - contourpy=1.2.0
  - cryptography=42.0.2
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - expat=2.5.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - freexl=2.0.0
  - gdal=3.6.2
  - geos=3.8.0
  - geotiff=1.7.0
  - giflib=5.2.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - hdf4=4.2.13
  - hdf5=1.12.1
  - icu=73.1
  - iniconfig=1.1.1
  - intel-openmp=2023.1.0
  - jpeg=9e
  - json-c=0.16
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - kealib=1.5.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libcurl=8.5.0
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgdal=3.6.2
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libkml=1.3.0
  - libllvm14=14.0.6
  - libnetcdf=4.8.1
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libpq=12.17
  - libspatialite=5.1.0
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - libzip=1.8.0
  - lz4-c=1.9.4
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - minizip=4.0.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - munkres=1.1.4
  - mysql=5.7.24
  - ncurses=6.4
  - nspr=4.35
  - nss=3.89.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.4.0
  - openssl=3.0.13
  - packaging=23.1
  - pcre2=10.42
  - pillow=10.2.0
  - pip=23.3.1
  - pixman=0.40.0
  - pluggy=1.0.0
  - ply=3.11
  - poppler=22.12.0
  - poppler-data=0.4.11
  - proj=9.3.1
  - pycparser=2.21
  - pycurl=7.45.2
  - pyopenssl=24.0.0
  - pyparsing=3.0.9
  - pyproj=3.6.1
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pyshp=2.3.1
  - pytest=7.4.0
  - python=3.11.8
  - python-dateutil=2.8.2
  - qhull=2020.2
  - qt-main=5.15.2
  - readline=8.2
  - referencing=0.30.2
  - rpds-py=0.10.6
  - setuptools=68.2.2
  - shapely=1.7.0
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tiledb=2.3.3
  - tk=8.6.12
  - tornado=6.3.3
  - tzdata=2024a
  - uriparser=0.9.7
  - wheel=0.41.2
  - xerces-c=3.2.4
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - jwt==1.3.1
      - lxml==5.1.0
      - portpicker==1.6.0
      - psutil==5.9.8
      - pygc==1.3.0
      - pykml==0.2.0
      - xlsxwriter==3.2.0
