"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import src.harness.api.google.google_client
from src.harness.api.google.google_client.model.cell_tower import CellTower
from src.harness.api.google.google_client.model.wi_fi_access_point import WiFiAccessPoint
globals()['CellTower'] = CellTower
globals()['WiFiAccessPoint'] = WiFiAccessPoint
from src.harness.api.google.google_client.model.geolocation_request import GeolocationRequest


class TestGeolocationRequest(unittest.TestCase):
    """GeolocationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeolocationRequest(self):
        """Test GeolocationRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GeolocationRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
