"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import src.harness.api.google.google_client
from src.harness.api.google.google_client.model.place_autocomplete_matched_substring import PlaceAutocompleteMatchedSubstring
globals()['PlaceAutocompleteMatchedSubstring'] = PlaceAutocompleteMatchedSubstring
from src.harness.api.google.google_client.model.place_autocomplete_structured_format import PlaceAutocompleteStructuredFormat


class TestPlaceAutocompleteStructuredFormat(unittest.TestCase):
    """PlaceAutocompleteStructuredFormat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlaceAutocompleteStructuredFormat(self):
        """Test PlaceAutocompleteStructuredFormat"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PlaceAutocompleteStructuredFormat()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
