"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import unittest

import src.harness.api.google.google_client
from src.harness.api.google.google_client.api.elevation_api_api import ElevationAPIApi  # noqa: E501


class TestElevationAPIApi(unittest.TestCase):
    """ElevationAPIApi unit test stubs"""

    def setUp(self):
        self.api = ElevationAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_elevation(self):
        """Test case for elevation

        """
        pass


if __name__ == '__main__':
    unittest.main()
