"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import unittest

import src.harness.api.google.google_client
from src.harness.api.google.google_client.api.street_view_api_api import StreetViewAPIApi  # noqa: E501


class TestStreetViewAPIApi(unittest.TestCase):
    """StreetViewAPIApi unit test stubs"""

    def setUp(self):
        self.api = StreetViewAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_street_view(self):
        """Test case for street_view

        """
        pass

    def test_street_view_metadata(self):
        """Test case for street_view_metadata

        """
        pass


if __name__ == '__main__':
    unittest.main()
