"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import src.harness.api.google.google_client
from src.harness.api.google.google_client.model.place import Place
from src.harness.api.google.google_client.model.places_search_status import PlacesSearchStatus
globals()['Place'] = Place
globals()['PlacesSearchStatus'] = PlacesSearchStatus
from src.harness.api.google.google_client.model.places_nearby_search_response import PlacesNearbySearchResponse


class TestPlacesNearbySearchResponse(unittest.TestCase):
    """PlacesNearbySearchResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlacesNearbySearchResponse(self):
        """Test PlacesNearbySearchResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PlacesNearbySearchResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
