"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import src.harness.api.google.google_client
from src.harness.api.google.google_client.model.distance_matrix_row import DistanceMatrixRow
from src.harness.api.google.google_client.model.distance_matrix_status import DistanceMatrixStatus
globals()['DistanceMatrixRow'] = DistanceMatrixRow
globals()['DistanceMatrixStatus'] = DistanceMatrixStatus
from src.harness.api.google.google_client.model.distance_matrix_response import DistanceMatrixResponse


class TestDistanceMatrixResponse(unittest.TestCase):
    """DistanceMatrixResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDistanceMatrixResponse(self):
        """Test DistanceMatrixResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DistanceMatrixResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
