"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import src.harness.api.google.google_client
from src.harness.api.google.google_client.model.place import Place
from src.harness.api.google.google_client.model.places_search_status import PlacesSearchStatus
globals()['Place'] = Place
globals()['PlacesSearchStatus'] = PlacesSearchStatus
from src.harness.api.google.google_client.model.places_text_search_response import PlacesTextSearchResponse


class TestPlacesTextSearchResponse(unittest.TestCase):
    """PlacesTextSearchResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlacesTextSearchResponse(self):
        """Test PlacesTextSearchResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PlacesTextSearchResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
