"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import src.harness.api.google.google_client
from src.harness.api.google.google_client.model.street_view_status import StreetViewStatus


class TestStreetViewStatus(unittest.TestCase):
    """StreetViewStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStreetViewStatus(self):
        """Test StreetViewStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StreetViewStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
