"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import src.harness.api.google.google_client
from src.harness.api.google.google_client.model.directions_polyline import DirectionsPolyline
from src.harness.api.google.google_client.model.directions_transit_details import DirectionsTransitDetails
from src.harness.api.google.google_client.model.lat_lng_literal import LatLngLiteral
from src.harness.api.google.google_client.model.text_value_object import TextValueObject
from src.harness.api.google.google_client.model.travel_mode import TravelMode
globals()['DirectionsPolyline'] = DirectionsPolyline
globals()['DirectionsTransitDetails'] = DirectionsTransitDetails
globals()['LatLngLiteral'] = LatLngLiteral
globals()['TextValueObject'] = TextValueObject
globals()['TravelMode'] = TravelMode
from src.harness.api.google.google_client.model.directions_step import DirectionsStep


class TestDirectionsStep(unittest.TestCase):
    """DirectionsStep unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDirectionsStep(self):
        """Test DirectionsStep"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DirectionsStep()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
