"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import src.harness.api.google.google_client
from src.harness.api.google.google_client.model.directions_step import DirectionsStep
from src.harness.api.google.google_client.model.directions_traffic_speed_entry import DirectionsTrafficSpeedEntry
from src.harness.api.google.google_client.model.directions_via_waypoint import DirectionsViaWaypoint
from src.harness.api.google.google_client.model.lat_lng_literal import LatLngLiteral
from src.harness.api.google.google_client.model.text_value_object import TextValueObject
from src.harness.api.google.google_client.model.time_zone_text_value_object import TimeZoneTextValueObject
globals()['DirectionsStep'] = DirectionsStep
globals()['DirectionsTrafficSpeedEntry'] = DirectionsTrafficSpeedEntry
globals()['DirectionsViaWaypoint'] = DirectionsViaWaypoint
globals()['LatLngLiteral'] = LatLngLiteral
globals()['TextValueObject'] = TextValueObject
globals()['TimeZoneTextValueObject'] = TimeZoneTextValueObject
from src.harness.api.google.google_client.model.directions_leg import DirectionsLeg


class TestDirectionsLeg(unittest.TestCase):
    """DirectionsLeg unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDirectionsLeg(self):
        """Test DirectionsLeg"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DirectionsLeg()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
