"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import src.harness.api.google.google_client
from src.harness.api.google.google_client.model.latitude_longitude_literal import LatitudeLongitudeLiteral


class TestLatitudeLongitudeLiteral(unittest.TestCase):
    """LatitudeLongitudeLiteral unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLatitudeLongitudeLiteral(self):
        """Test LatitudeLongitudeLiteral"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LatitudeLongitudeLiteral()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
