"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import src.harness.api.google.google_client
from src.harness.api.google.google_client.model.elevation_result import ElevationResult
from src.harness.api.google.google_client.model.elevation_status import ElevationStatus
globals()['ElevationResult'] = ElevationResult
globals()['ElevationStatus'] = ElevationStatus
from src.harness.api.google.google_client.model.elevation_response import ElevationResponse


class TestElevationResponse(unittest.TestCase):
    """ElevationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testElevationResponse(self):
        """Test ElevationResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ElevationResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
