"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import unittest

import src.harness.api.google.google_client
from src.harness.api.google.google_client.api.time_zone_api_api import TimeZoneAPIApi  # noqa: E501


class TestTimeZoneAPIApi(unittest.TestCase):
    """TimeZoneAPIApi unit test stubs"""

    def setUp(self):
        self.api = TimeZoneAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_timezone(self):
        """Test case for timezone

        """
        pass


if __name__ == '__main__':
    unittest.main()
