"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import src.harness.api.google.google_client
from src.harness.api.google.google_client.model.place import Place
from src.harness.api.google.google_client.model.places_search_status import PlacesSearchStatus
globals()['Place'] = Place
globals()['PlacesSearchStatus'] = PlacesSearchStatus
from src.harness.api.google.google_client.model.places_find_place_from_text_response import PlacesFindPlaceFromTextResponse


class TestPlacesFindPlaceFromTextResponse(unittest.TestCase):
    """PlacesFindPlaceFromTextResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlacesFindPlaceFromTextResponse(self):
        """Test PlacesFindPlaceFromTextResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PlacesFindPlaceFromTextResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
