"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import unittest

import src.harness.api.google.google_client
from src.harness.api.google.google_client.api.distance_matrix_api_api import DistanceMatrixAPIApi  # noqa: E501


class TestDistanceMatrixAPIApi(unittest.TestCase):
    """DistanceMatrixAPIApi unit test stubs"""

    def setUp(self):
        self.api = DistanceMatrixAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_distance_matrix(self):
        """Test case for distance_matrix

        """
        pass


if __name__ == '__main__':
    unittest.main()
