"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import src.harness.api.google.google_client
from src.harness.api.google.google_client.model.lat_lng_literal import LatLngLiteral
globals()['LatLngLiteral'] = LatLngLiteral
from src.harness.api.google.google_client.model.directions_via_waypoint import DirectionsViaWaypoint


class TestDirectionsViaWaypoint(unittest.TestCase):
    """DirectionsViaWaypoint unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDirectionsViaWaypoint(self):
        """Test DirectionsViaWaypoint"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DirectionsViaWaypoint()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
