"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import unittest

import src.harness.api.google.google_client
from src.harness.api.google.google_client.api.roads_api_api import RoadsAPIApi  # noqa: E501


class TestRoadsAPIApi(unittest.TestCase):
    """RoadsAPIApi unit test stubs"""

    def setUp(self):
        self.api = RoadsAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_nearest_roads(self):
        """Test case for nearest_roads

        """
        pass

    def test_snap_to_roads(self):
        """Test case for snap_to_roads

        """
        pass


if __name__ == '__main__':
    unittest.main()
