"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import src.harness.api.google.google_client
from src.harness.api.google.google_client.model.distance_matrix_element_status import DistanceMatrixElementStatus
from src.harness.api.google.google_client.model.fare import Fare
from src.harness.api.google.google_client.model.text_value_object import TextValueObject
globals()['DistanceMatrixElementStatus'] = DistanceMatrixElementStatus
globals()['Fare'] = Fare
globals()['TextValueObject'] = TextValueObject
from src.harness.api.google.google_client.model.distance_matrix_element import DistanceMatrixElement


class TestDistanceMatrixElement(unittest.TestCase):
    """DistanceMatrixElement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDistanceMatrixElement(self):
        """Test DistanceMatrixElement"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DistanceMatrixElement()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
