"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import unittest

import src.harness.api.google.google_client
from src.harness.api.google.google_client.api.places_api_api import PlacesAPIApi  # noqa: E501


class TestPlacesAPIApi(unittest.TestCase):
    """PlacesAPIApi unit test stubs"""

    def setUp(self):
        self.api = PlacesAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_autocomplete(self):
        """Test case for autocomplete

        """
        pass

    def test_find_place_from_text(self):
        """Test case for find_place_from_text

        """
        pass

    def test_nearby_search(self):
        """Test case for nearby_search

        """
        pass

    def test_place_details(self):
        """Test case for place_details

        """
        pass

    def test_place_photo(self):
        """Test case for place_photo

        """
        pass

    def test_query_autocomplete(self):
        """Test case for query_autocomplete

        """
        pass

    def test_text_search(self):
        """Test case for text_search

        """
        pass


if __name__ == '__main__':
    unittest.main()
