"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import src.harness.api.google.google_client
from src.harness.api.google.google_client.model.bounds import Bounds
from src.harness.api.google.google_client.model.directions_leg import DirectionsLeg
from src.harness.api.google.google_client.model.directions_polyline import DirectionsPolyline
from src.harness.api.google.google_client.model.fare import Fare
globals()['Bounds'] = Bounds
globals()['DirectionsLeg'] = DirectionsLeg
globals()['DirectionsPolyline'] = DirectionsPolyline
globals()['Fare'] = Fare
from src.harness.api.google.google_client.model.directions_route import DirectionsRoute


class TestDirectionsRoute(unittest.TestCase):
    """DirectionsRoute unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDirectionsRoute(self):
        """Test DirectionsRoute"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DirectionsRoute()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
