"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import src.harness.api.google.google_client
from src.harness.api.google.google_client.model.address_component import AddressComponent
from src.harness.api.google.google_client.model.geometry import Geometry
from src.harness.api.google.google_client.model.place_opening_hours import PlaceOpeningHours
from src.harness.api.google.google_client.model.place_photo import PlacePhoto
from src.harness.api.google.google_client.model.place_review import PlaceReview
from src.harness.api.google.google_client.model.plus_code import PlusCode
globals()['AddressComponent'] = AddressComponent
globals()['Geometry'] = Geometry
globals()['PlaceOpeningHours'] = PlaceOpeningHours
globals()['PlacePhoto'] = PlacePhoto
globals()['PlaceReview'] = PlaceReview
globals()['PlusCode'] = PlusCode
from src.harness.api.google.google_client.model.place import Place


class TestPlace(unittest.TestCase):
    """Place unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlace(self):
        """Test Place"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Place()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
