"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import src.harness.api.google.google_client
from src.harness.api.google.google_client.model.lat_lng_array_string import LatLngArrayString


class TestLatLngArrayString(unittest.TestCase):
    """LatLngArrayString unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLatLngArrayString(self):
        """Test LatLngArrayString"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LatLngArrayString()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
