"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import src.harness.api.google.google_client
from src.harness.api.google.google_client.model.bounds import Bounds
from src.harness.api.google.google_client.model.lat_lng_literal import LatLngLiteral
globals()['Bounds'] = Bounds
globals()['LatLngLiteral'] = LatLngLiteral
from src.harness.api.google.google_client.model.geocoding_geometry import GeocodingGeometry


class TestGeocodingGeometry(unittest.TestCase):
    """GeocodingGeometry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeocodingGeometry(self):
        """Test GeocodingGeometry"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GeocodingGeometry()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
