"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import unittest

import src.harness.api.google.google_client
from src.harness.api.google.google_client.api.directions_api_api import DirectionsAPIApi  # noqa: E501


class TestDirectionsAPIApi(unittest.TestCase):
    """DirectionsAPIApi unit test stubs"""

    def setUp(self):
        self.api = DirectionsAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_directions(self):
        """Test case for directions

        """
        pass


if __name__ == '__main__':
    unittest.main()
