"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import src.harness.api.google.google_client
from src.harness.api.google.google_client.model.place_opening_hours_period_detail import PlaceOpeningHoursPeriodDetail
globals()['PlaceOpeningHoursPeriodDetail'] = PlaceOpeningHoursPeriodDetail
from src.harness.api.google.google_client.model.place_opening_hours_period import PlaceOpeningHoursPeriod


class TestPlaceOpeningHoursPeriod(unittest.TestCase):
    """PlaceOpeningHoursPeriod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlaceOpeningHoursPeriod(self):
        """Test PlaceOpeningHoursPeriod"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PlaceOpeningHoursPeriod()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
