"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import unittest

import src.harness.api.google.google_client
from src.harness.api.google.google_client.api.geocoding_api_api import GeocodingAPIApi  # noqa: E501


class TestGeocodingAPIApi(unittest.TestCase):
    """GeocodingAPIApi unit test stubs"""

    def setUp(self):
        self.api = GeocodingAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_geocode(self):
        """Test case for geocode

        """
        pass


if __name__ == '__main__':
    unittest.main()
