"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import src.harness.api.google.google_client
from src.harness.api.google.google_client.model.directions_transit_line import DirectionsTransitLine
from src.harness.api.google.google_client.model.directions_transit_stop import DirectionsTransitStop
from src.harness.api.google.google_client.model.time_zone_text_value_object import TimeZoneTextValueObject
globals()['DirectionsTransitLine'] = DirectionsTransitLine
globals()['DirectionsTransitStop'] = DirectionsTransitStop
globals()['TimeZoneTextValueObject'] = TimeZoneTextValueObject
from src.harness.api.google.google_client.model.directions_transit_details import DirectionsTransitDetails


class TestDirectionsTransitDetails(unittest.TestCase):
    """DirectionsTransitDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDirectionsTransitDetails(self):
        """Test DirectionsTransitDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DirectionsTransitDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
