"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import src.harness.api.google.google_client
from src.harness.api.google.google_client.model.geocoding_result import GeocodingResult
from src.harness.api.google.google_client.model.geocoding_status import GeocodingStatus
from src.harness.api.google.google_client.model.plus_code import PlusCode
globals()['GeocodingResult'] = GeocodingResult
globals()['GeocodingStatus'] = GeocodingStatus
globals()['PlusCode'] = PlusCode
from src.harness.api.google.google_client.model.geocoding_response import GeocodingResponse


class TestGeocodingResponse(unittest.TestCase):
    """GeocodingResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeocodingResponse(self):
        """Test GeocodingResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GeocodingResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
