"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import src.harness.api.google.google_client
from src.harness.api.google.google_client.model.place_autocomplete_prediction import PlaceAutocompletePrediction
from src.harness.api.google.google_client.model.places_autocomplete_status import PlacesAutocompleteStatus
globals()['PlaceAutocompletePrediction'] = PlaceAutocompletePrediction
globals()['PlacesAutocompleteStatus'] = PlacesAutocompleteStatus
from src.harness.api.google.google_client.model.places_autocomplete_response import PlacesAutocompleteResponse


class TestPlacesAutocompleteResponse(unittest.TestCase):
    """PlacesAutocompleteResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlacesAutocompleteResponse(self):
        """Test PlacesAutocompleteResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PlacesAutocompleteResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
