"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import src.harness.api.google.google_client
from src.harness.api.google.google_client.model.snapped_point import SnappedPoint
globals()['SnappedPoint'] = SnappedPoint
from src.harness.api.google.google_client.model.nearest_roads_response import NearestRoadsResponse


class TestNearestRoadsResponse(unittest.TestCase):
    """NearestRoadsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNearestRoadsResponse(self):
        """Test NearestRoadsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NearestRoadsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
