"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import src.harness.api.google.google_client
from src.harness.api.google.google_client.model.place import Place
from src.harness.api.google.google_client.model.places_details_status import PlacesDetailsStatus
globals()['Place'] = Place
globals()['PlacesDetailsStatus'] = PlacesDetailsStatus
from src.harness.api.google.google_client.model.places_details_response import PlacesDetailsResponse


class TestPlacesDetailsResponse(unittest.TestCase):
    """PlacesDetailsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlacesDetailsResponse(self):
        """Test PlacesDetailsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PlacesDetailsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
