"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import src.harness.api.google.google_client
from src.harness.api.google.google_client.model.place_autocomplete_prediction import PlaceAutocompletePrediction
from src.harness.api.google.google_client.model.places_autocomplete_status import PlacesAutocompleteStatus
globals()['PlaceAutocompletePrediction'] = PlaceAutocompletePrediction
globals()['PlacesAutocompleteStatus'] = PlacesAutocompleteStatus
from src.harness.api.google.google_client.model.places_query_autocomplete_response import PlacesQueryAutocompleteResponse


class TestPlacesQueryAutocompleteResponse(unittest.TestCase):
    """PlacesQueryAutocompleteResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlacesQueryAutocompleteResponse(self):
        """Test PlacesQueryAutocompleteResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PlacesQueryAutocompleteResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
