"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import src.harness.api.google.google_client
from src.harness.api.google.google_client.model.cell_tower import CellTower


class TestCellTower(unittest.TestCase):
    """CellTower unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCellTower(self):
        """Test CellTower"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CellTower()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
