"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import src.harness.api.google.google_client
from src.harness.api.google.google_client.model.directions_transit_agency import DirectionsTransitAgency
from src.harness.api.google.google_client.model.directions_transit_vehicle import DirectionsTransitVehicle
globals()['DirectionsTransitAgency'] = DirectionsTransitAgency
globals()['DirectionsTransitVehicle'] = DirectionsTransitVehicle
from src.harness.api.google.google_client.model.directions_transit_line import DirectionsTransitLine


class TestDirectionsTransitLine(unittest.TestCase):
    """DirectionsTransitLine unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDirectionsTransitLine(self):
        """Test DirectionsTransitLine"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DirectionsTransitLine()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
