"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import src.harness.api.google.google_client
from src.harness.api.google.google_client.model.directions_geocoded_waypoint import DirectionsGeocodedWaypoint
from src.harness.api.google.google_client.model.directions_route import DirectionsRoute
from src.harness.api.google.google_client.model.directions_status import DirectionsStatus
from src.harness.api.google.google_client.model.travel_mode import TravelMode
globals()['DirectionsGeocodedWaypoint'] = DirectionsGeocodedWaypoint
globals()['DirectionsRoute'] = DirectionsRoute
globals()['DirectionsStatus'] = DirectionsStatus
globals()['TravelMode'] = TravelMode
from src.harness.api.google.google_client.model.directions_response import DirectionsResponse


class TestDirectionsResponse(unittest.TestCase):
    """DirectionsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDirectionsResponse(self):
        """Test DirectionsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DirectionsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
