"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import src.harness.api.google.google_client
from src.harness.api.google.google_client.model.nearest_roads_error import NearestRoadsError
globals()['NearestRoadsError'] = NearestRoadsError
from src.harness.api.google.google_client.model.nearest_roads_error_response import NearestRoadsErrorResponse


class TestNearestRoadsErrorResponse(unittest.TestCase):
    """NearestRoadsErrorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNearestRoadsErrorResponse(self):
        """Test NearestRoadsErrorResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NearestRoadsErrorResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
