REGION_TYPE_DENSE_URBAN = 'DENSE URBAN'
REGION_TYPE_RURAL = 'RURAL'
REGION_TYPE_SUBURBAN = 'SUBURBAN'
REGION_TYPE_URBAN = 'URBAN'

ALL_REGION_TYPES = [
    REGION_TYPE_DENSE_URBAN,
    REGION_TYPE_RURAL,
    REGION_TYPE_SUBURBAN,
    REGION_TYPE_URBAN
]

DPA_CALCULATOR_LOGGER_NAME = 'DPA_CALCULATOR_LOGGER'
REGION_TYPE_TYPE = str