"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from src.harness.api.google.google_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)
from ..model_utils import OpenApiModel
from src.harness.api.google.google_client.exceptions import ApiAttributeError


def lazy_import():
    from src.harness.api.google.google_client.model.directions_step import DirectionsStep
    from src.harness.api.google.google_client.model.directions_traffic_speed_entry import DirectionsTrafficSpeedEntry
    from src.harness.api.google.google_client.model.directions_via_waypoint import DirectionsViaWaypoint
    from src.harness.api.google.google_client.model.lat_lng_literal import LatLngLiteral
    from src.harness.api.google.google_client.model.text_value_object import TextValueObject
    from src.harness.api.google.google_client.model.time_zone_text_value_object import TimeZoneTextValueObject
    globals()['DirectionsStep'] = DirectionsStep
    globals()['DirectionsTrafficSpeedEntry'] = DirectionsTrafficSpeedEntry
    globals()['DirectionsViaWaypoint'] = DirectionsViaWaypoint
    globals()['LatLngLiteral'] = LatLngLiteral
    globals()['TextValueObject'] = TextValueObject
    globals()['TimeZoneTextValueObject'] = TimeZoneTextValueObject


class DirectionsLeg(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'end_address': (str,),  # noqa: E501
            'end_location': (LatLngLiteral,),  # noqa: E501
            'start_address': (str,),  # noqa: E501
            'start_location': (LatLngLiteral,),  # noqa: E501
            'steps': ([DirectionsStep],),  # noqa: E501
            'traffic_speed_entry': ([DirectionsTrafficSpeedEntry],),  # noqa: E501
            'via_waypoint': ([DirectionsViaWaypoint],),  # noqa: E501
            'arrival_time': (TimeZoneTextValueObject,),  # noqa: E501
            'departure_time': (TimeZoneTextValueObject,),  # noqa: E501
            'distance': (TextValueObject,),  # noqa: E501
            'duration': (TextValueObject,),  # noqa: E501
            'duration_in_traffic': (TextValueObject,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'end_address': 'end_address',  # noqa: E501
        'end_location': 'end_location',  # noqa: E501
        'start_address': 'start_address',  # noqa: E501
        'start_location': 'start_location',  # noqa: E501
        'steps': 'steps',  # noqa: E501
        'traffic_speed_entry': 'traffic_speed_entry',  # noqa: E501
        'via_waypoint': 'via_waypoint',  # noqa: E501
        'arrival_time': 'arrival_time',  # noqa: E501
        'departure_time': 'departure_time',  # noqa: E501
        'distance': 'distance',  # noqa: E501
        'duration': 'duration',  # noqa: E501
        'duration_in_traffic': 'duration_in_traffic',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, end_address, end_location, start_address, start_location, steps, traffic_speed_entry, via_waypoint, *args, **kwargs):  # noqa: E501
        """DirectionsLeg - a model defined in OpenAPI

        Args:
            end_address (str): Contains the human-readable address (typically a street address) from reverse geocoding the `end_location` of this leg. This content is meant to be read as-is. Do not programmatically parse the formatted address.
            end_location (LatLngLiteral):
            start_address (str): Contains the human-readable address (typically a street address) resulting from reverse geocoding the `start_location` of this leg. This content is meant to be read as-is. Do not programmatically parse the formatted address.
            start_location (LatLngLiteral):
            steps ([DirectionsStep]): An array of steps denoting information about each separate step of the leg of the journey.
            traffic_speed_entry ([DirectionsTrafficSpeedEntry]): Information about traffic speed along the leg.
            via_waypoint ([DirectionsViaWaypoint]): The locations of via waypoints along this leg.

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            arrival_time (TimeZoneTextValueObject): [optional]  # noqa: E501
            departure_time (TimeZoneTextValueObject): [optional]  # noqa: E501
            distance (TextValueObject): [optional]  # noqa: E501
            duration (TextValueObject): [optional]  # noqa: E501
            duration_in_traffic (TextValueObject): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.end_address = end_address
        self.end_location = end_location
        self.start_address = start_address
        self.start_location = start_location
        self.steps = steps
        self.traffic_speed_entry = traffic_speed_entry
        self.via_waypoint = via_waypoint
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, end_address, end_location, start_address, start_location, steps, traffic_speed_entry, via_waypoint, *args, **kwargs):  # noqa: E501
        """DirectionsLeg - a model defined in OpenAPI

        Args:
            end_address (str): Contains the human-readable address (typically a street address) from reverse geocoding the `end_location` of this leg. This content is meant to be read as-is. Do not programmatically parse the formatted address.
            end_location (LatLngLiteral):
            start_address (str): Contains the human-readable address (typically a street address) resulting from reverse geocoding the `start_location` of this leg. This content is meant to be read as-is. Do not programmatically parse the formatted address.
            start_location (LatLngLiteral):
            steps ([DirectionsStep]): An array of steps denoting information about each separate step of the leg of the journey.
            traffic_speed_entry ([DirectionsTrafficSpeedEntry]): Information about traffic speed along the leg.
            via_waypoint ([DirectionsViaWaypoint]): The locations of via waypoints along this leg.

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            arrival_time (TimeZoneTextValueObject): [optional]  # noqa: E501
            departure_time (TimeZoneTextValueObject): [optional]  # noqa: E501
            distance (TextValueObject): [optional]  # noqa: E501
            duration (TextValueObject): [optional]  # noqa: E501
            duration_in_traffic (TextValueObject): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.end_address = end_address
        self.end_location = end_location
        self.start_address = start_address
        self.start_location = start_location
        self.steps = steps
        self.traffic_speed_entry = traffic_speed_entry
        self.via_waypoint = via_waypoint
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
