"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import worldpop_client
from worldpop_client.model.stats_response import StatsResponse


class TestStatsResponse(unittest.TestCase):
    """StatsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatsResponse(self):
        """Test StatsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StatsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
