"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import unittest

import worldpop_client
from worldpop_client.api.tasks_api import TasksApi  # noqa: E501


class TestTasksApi(unittest.TestCase):
    """TasksApi unit test stubs"""

    def setUp(self):
        self.api = TasksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tasks_task_id_get(self):
        """Test case for tasks_task_id_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
