"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import worldpop_client
from worldpop_client.model.tasks_response import TasksResponse


class TestTasksResponse(unittest.TestCase):
    """TasksResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTasksResponse(self):
        """Test TasksResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TasksResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
