"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import worldpop_client
from worldpop_client.model.geo_json_features import GeoJsonFeatures
globals()['GeoJsonFeatures'] = GeoJsonFeatures
from worldpop_client.model.geo_json import GeoJson


class TestGeoJson(unittest.TestCase):
    """GeoJson unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeoJson(self):
        """Test GeoJson"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GeoJson()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
