"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import worldpop_client
from worldpop_client.model.geometry_object import GeometryObject
globals()['GeometryObject'] = GeometryObject
from worldpop_client.model.geo_json_features import GeoJsonFeatures


class TestGeoJsonFeatures(unittest.TestCase):
    """GeoJsonFeatures unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeoJsonFeatures(self):
        """Test GeoJsonFeatures"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GeoJsonFeatures()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
