"""
    Google Maps Platform

    API Specification for Google Maps Platform  # noqa: E501

    The version of the OpenAPI document: 1.17.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import worldpop_client
from worldpop_client.model.geometry_object import GeometryObject


class TestGeometryObject(unittest.TestCase):
    """GeometryObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeometryObject(self):
        """Test GeometryObject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GeometryObject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
